<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Contracts\**" />
    <Compile Remove="MappingProfiles\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Contracts\**" />
    <EmbeddedResource Remove="MappingProfiles\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Contracts\**" />
    <None Remove="MappingProfiles\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeautyTechPro.Domain\BeautyTechPro.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
